import About from "@/components/About";
import React from "react";
export const metadata = {
  title: "Faiyaj Bin Ahmed | About",
  description: "Generated by create next app",
};
const page = () => {
  return <About />;
};

export default page;
