import Projects from "@/components/Projects";
import React from "react";
export const metadata = {
  title: "Faiyaj Bin Ahmed | Projects",
  description: "Generated by create next app",
};
const page = () => {
  return <Projects />;
};

export default page;
